id: 1d56e9c2cc1f4a25b6e65a537fdcf43e
initial_creation_type: ocr
source_metadata:
  volumes:
    afdebd45138c466a822eb7279e0296d5:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བསམ་གྱིས་མི་ཁྱབ་པར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
